// Every UI string, from docs/COPY_DECK.md. Sentence case, no exclamation marks.
// Straight quotes here become typographic at display time.

export const COPY = {
  wordmark: 'unsetld',
  notificationTitle: 'unsetld',
  volumeLabel: (v: number) => `VOL. ${String(v).padStart(3, '0')}`,

  o1: {
    figure: 'FIG. 01',
    defs: ['Not finished.', 'Not willing to settle for less.'],
    begin: 'Begin',
  },
  o2: {
    caption: 'One line every morning. Swipe up for the next.',
    next: 'Next',
    continue: 'Continue',
  },
  standard: {
    title: 'Set your standard.',
    body: "Pick three. Each night you'll mark whether you held them. Only you see this.",
    writeOwn: 'Write your own',
    placeholder: 'Say it plainly.',
    counter: (n: number) => `${n} OF 3 CHOSEN`,
    button: 'Set the standard',
    save: 'Save',
  },
  chapters: {
    title: 'Choose your chapters.',
    body: 'Your daily lines come from these. Free includes Discipline and one more. Full Edition opens all seven.',
    always: 'ALWAYS',
    button: 'Continue',
    sheetTitle: 'Chapters',
    sheetHeader: (vol: number, n: number) => `VOLUME ${String(vol).padStart(3, '0')} · ${n} LINES`,
    allMine: 'All my chapters',
    saved: 'Saved',
    yourLines: 'Your lines',
    locked: 'FULL EDITION',
    lockedTitle: (name: string) => `${name} is part of Full Edition.`,
    makeFree: (name: string) => `Make ${name} my free chapter`,
    seeFull: 'See Full Edition',
    cancel: 'Cancel',
  },
  day: {
    title: 'Set your day.',
    previewBody: 'Every time you check your phone, you pay to get back in.',
    perDay: 'Reminders a day',
    perDayNote: 'More than 3 a day is part of Full Edition.',
    first: 'First reminder',
    last: 'Last reminder',
    night: 'Night check',
    nightNote: 'One question at night: did you hold your standard?',
    done: 'Done',
    allow: 'Allow reminders',
    notNow: 'Not now',
    remindersTitle: 'Reminders',
    save: 'Save',
    permOff: 'Notifications are off for unsetld.',
    openSettings: 'Open Settings',
  },
  widget: {
    title: 'Put it on your lock screen.',
    tabs: ['Lock Screen', 'Home Screen'] as const,
    lockSteps: [
      'Touch and hold your lock screen, then tap Customize.',
      'Tap Lock Screen, then the space under the clock.',
      'Choose unsetld, then Line.',
    ],
    homeSteps: [
      'Touch and hold an empty spot on your home screen.',
      'Tap Edit, then Add Widget.',
      'Search unsetld and choose a size.',
    ],
    done: 'Done',
    later: 'Later',
    pageTitle: 'Add a widget',
  },
  reader: {
    dayHead: (n: number) => `DAY ${n}`,
    only: (name: string) => `${name.toUpperCase()} ONLY`,
    saved: 'SAVED',
    volumeOnly: (v: number) => `VOLUME ${String(v).padStart(3, '0')}`,
    chapters: 'Chapters',
    hint: 'Swipe up for the next line.',
    menu: {
      share: 'Share',
      copy: 'Copy line',
      save: 'Save',
      unsave: 'Remove from saved',
      hide: "Don't show this line again",
      cancel: 'Cancel',
    },
    a11y: {
      save: 'Save line',
      unsave: 'Remove from saved',
      share: 'Share line',
      chapters: 'Chapters',
      colorway: 'Colorway',
      record: 'Your record',
      close: 'Close',
      back: 'Back',
      showMix: 'Back to all my chapters',
    },
  },
  night: {
    label: 'NIGHT CHECK',
    question: 'Did you hold your standard today?',
    held: 'Held',
    notToday: 'Not today',
    heldTitle: 'Held.',
    notedTitle: 'Noted.',
    heldBody: (n: number) => `Day ${n} is on record.`,
    notedBody: (n: number) => `Day ${n} is still on record.`,
  },
  end: {
    title: ["You've read enough lines like this one.", 'Go do the work.'],
    sub: 'Ten more tomorrow.',
    link: 'Read more with Full Edition',
  },
  oneTime: {
    access: {
      label: 'ACCESS',
      title: 'The days add up to something.',
      body: 'Day 7 opens early access to every UNSETLD drop. Day 30 opens a member price. None of it can be bought.',
      link: 'See your record',
    },
    volume: {
      label: (v: number) => `VOLUME ${String(v).padStart(3, '0')}`,
      title: 'Forty new lines.',
      body: 'Across all seven chapters, starting today.',
      link: 'Read them',
    },
    exhausted: {
      title: "You've read every line in your chapters.",
      body: 'Add a chapter, or start again from the first line.',
      chapters: 'Chapters',
      again: 'Start again',
    },
  },
  colorway: {
    title: 'Colorway',
    locked: 'FULL EDITION',
    lockedBar: (name: string) => `${name} is part of Full Edition.`,
    seeFull: 'See Full Edition',
  },
  share: {
    tabs: ['Story', 'Post'] as const,
    button: 'Share',
    copy: 'Copy line',
    copied: 'Copied',
    previewNote: 'Sharing opens the iOS share sheet in the app.',
  },
  saved: {
    title: 'Saved',
    remove: 'Remove from saved',
    emptyTitle: 'Nothing saved yet.',
    emptyBody: 'Double-tap a line to keep it here.',
  },
  yours: {
    title: 'Your lines',
    write: 'Write a line',
    placeholder: 'Write the line you need to read.',
    edit: 'Edit',
    delete: 'Delete',
    footnote: 'Your lines stay on this phone. They show up in your daily lines and can go on your widgets.',
    lockedTitle: 'Your lines are part of Full Edition.',
    lockedBody: 'Write the lines you need to read. They show up in your daily lines and on your widgets.',
    seeFull: 'See Full Edition',
    max: 110,
  },
  record: {
    settings: 'Settings',
    label: 'RECORD',
    daysOnRecord: (n: number) => (n === 1 ? 'day on record' : 'days on record'),
    today: 'TODAY',
    run: 'RUN',
    longest: 'LONGEST',
    held: 'HELD',
    days: (n: number) => (n === 1 ? 'day' : 'days'),
    of: 'of',
    access: 'Access',
    details: 'Details',
    accessNote: "Earned with days on record. It can't be bought.",
    status: {
      open: 'OPEN',
      used: 'USED',
      paused: 'PAUSED',
      left: (n: number) => (n === 1 ? '1 DAY' : `${n} DAYS`),
    },
    pausedNote: 'Access is paused. Put 7 days on record to open it again.',
    memberOpen: 'Your member price is open.',
    memberLink: 'Use it at unsetld.com',
  },
  milestone: {
    termsLink: 'Access terms',
    signInNote: 'Sign in to use access. It takes one tap.',
    usedNote: "You've used this collection's member price. It opens again with the next collection.",
    networkError: "Couldn't reach unsetld.com. Try again in a moment.",
    pausedError: 'Access is paused. Put 7 days on record to open it again.',
    claimedPatch: 'Added. It ships free with your next order.',
  },
  letter: {
    dayLabel: (d: number) => `DAY ${String(d).padStart(3, '0')}`,
    dayTitle: (d: number) => `Day ${d}.`,
    comebackSub: "You came back. That's the part that counts.",
    comebackBody: 'Early access and your member price are open again.',
    close: 'Close',
  },
  paywall: {
    restore: 'Restore',
    label: 'UNSETLD',
    title: 'Full Edition',
    description: 'Every chapter, every colorway, no daily limit.',
    spec: [
      ['CHAPTERS', 'All seven, and every new volume'],
      ['COLORWAYS', 'All ten, in the app and on your widgets'],
      ['LINES', 'No daily limit. Write your own.'],
      ['REMINDERS', 'Up to ten a day'],
    ] as const,
    plans: {
      annual: 'Annual',
      monthly: 'Monthly',
      lifetime: 'Lifetime',
    },
    sub: {
      annualTrial: (days: number) => `${days} days free, then billed yearly`,
      annual: 'Billed yearly',
      monthly: 'Billed monthly',
      lifetime: 'One payment',
    },
    unit: { annual: '/ year', monthly: '/ month', lifetime: 'once' },
    perMonth: (p: string) => `${p} a month`,
    save: (pct: number) => `Save ${pct}%`,
    timeline: (price: string) => [
      ['TODAY', 'Everything opens'],
      ['DAY 2', 'We remind you'],
      ['DAY 3', `${price} billed`],
    ],
    cta: {
      trial: 'Start free trial',
      annual: (p: string) => `Subscribe for ${p} a year`,
      monthly: (p: string) => `Subscribe for ${p} a month`,
      lifetime: (p: string) => `Buy for ${p}`,
    },
    fine: {
      trial: (days: number, p: string) =>
        `${days} days free, then ${p} per year. Renews automatically. Cancel any time in Settings at least 24 hours before the trial ends.`,
      annual: (p: string) => `${p} per year. Renews automatically. Cancel any time in Settings.`,
      monthly: (p: string) => `${p} per month. Renews automatically. Cancel any time in Settings.`,
      lifetime: (p: string) => `One payment of ${p}. No subscription.`,
    },
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    loading: '—',
    priceError: "Prices couldn't load. Check your connection.",
    tryAgain: 'Try again',
    failedTitle: "Purchase didn't go through.",
    failedBody: 'Nothing was charged. Try again in a moment.',
    restored: 'Full Edition restored.',
    noneTitle: 'Nothing to restore.',
    noneBody: "We couldn't find Full Edition on this Apple ID.",
    preview: 'Preview build. No charge.',
  },
  settings: {
    title: 'Settings',
    sections: {
      daily: 'DAILY',
      reading: 'READING',
      widgets: 'WIDGETS',
      unsetld: 'UNSETLD',
      full: 'FULL EDITION',
      about: 'ABOUT',
      tester: 'TESTER',
    },
    reminders: 'Reminders',
    remindersValue: (n: number, a: string, b: string) => (n === 0 ? 'Off' : `${n} a day, ${a} to ${b}`),
    night: 'Night check',
    standard: 'Your standard',
    chapters: 'Chapters',
    colorway: 'Colorway',
    strong: 'Strong language',
    strongNote: 'Some lines swear. They never appear on your lock screen, widgets or notifications.',
    saved: 'Saved',
    yourLines: 'Your lines',
    addWidget: 'Add a widget',
    dropAlerts: 'Drop alerts',
    dropNote: 'Tells you when a collection opens. Separate from your daily reminders. Off unless you turn it on.',
    account: 'Account',
    notSignedIn: 'Not signed in',
    plan: 'Plan',
    free: 'Free',
    restore: 'Restore purchases',
    record: 'How the record works',
    accessTerms: 'Access terms',
    contact: 'Contact',
    contactEmail: 'unsetldclothing@gmail.com',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    footer: (version: string, vol: number) => `unsetld · version ${version} · volume ${String(vol).padStart(3, '0')}`,
    devTools: 'Tester tools',
  },
  account: {
    title: 'Account',
    body: 'You only need an account to use access: early access, member prices and the patch. Saved lines, your lines and your record stay on this phone.',
    legal: "By signing in you confirm you're 18 or over and live in the US.",
    signedIn: (email: string) => `Signed in as ${email}`,
    signOut: 'Sign out',
    error: "Couldn't sign in. Try again in a moment.",
    previewButton: 'Sign in with Apple',
    previewNote: 'Preview build: sign-in is simulated.',
  },
  notifications: {
    night: 'Did you hold your standard today?',
    held: 'Held',
    notToday: 'Not today',
    trial: (p: string) => `Your free trial ends tomorrow. ${p} for the year starts then. Cancel any time in Settings.`,
    dropEarly: (c: string, when: string) => `Collection ${c} is open to you now. Everyone else gets it ${when}.`,
    dropPublic: (c: string, when: string) => `Collection ${c} opens ${when}.`,
  },
} as const;
