// Every UI string, from docs/COPY_DECK.md. Sentence case, no exclamation marks.
// Straight quotes here become typographic at display time.

export const COPY = {
  wordmark: 'unsetld',
  notificationTitle: 'unsetld',
  volumeLabel: (v: number) => `VOL. ${String(v).padStart(3, '0')}`,

  o1: {
    figure: 'FIG. 01',
    defs: ['Not finished.', 'Not willing to settle for less.'],
    begin: 'Begin',
  },
  o2: {
    caption: 'One line every morning. Then the work.',
    continue: 'Continue',
  },
  standard: {
    title: 'Set your standard.',
    body: "Pick three. They're your work every day, and each night you'll mark whether you held them. Only you see this.",
    writeOwn: 'Write your own',
    placeholder: 'Say it plainly.',
    counter: (n: number) => `${n} OF 3 CHOSEN`,
    button: 'Set the standard',
    save: 'Save',
  },
  chapters: {
    title: 'Choose your chapters.',
    body: 'Your daily task and lines come from these. Free includes Discipline and one more. Full Edition opens all seven.',
    always: 'ALWAYS',
    button: 'Continue',
    sheetTitle: 'Chapters',
    sheetHeader: (vol: number, n: number) => `VOLUME ${String(vol).padStart(3, '0')} · ${n} LINES`,
    sheetNote: 'Your daily task and lines come from these.',
    saved: 'Saved',
    yourLines: 'Your lines',
    locked: 'FULL EDITION',
    lockedTitle: (name: string) => `${name} is part of Full Edition.`,
    makeFree: (name: string) => `Make ${name} my free chapter`,
    seeFull: 'See Full Edition',
    cancel: 'Cancel',
  },
  day: {
    title: 'Set your day.',
    previewBody: 'Every time you check your phone, you pay to get back in.',
    perDay: 'Reminders a day',
    perDayNote: 'More than 3 a day is part of Full Edition.',
    first: 'First reminder',
    last: 'Last reminder',
    night: 'Night check',
    nightNote: 'One question at night: did you hold your standard?',
    done: 'Done',
    allow: 'Allow reminders',
    notNow: 'Not now',
    remindersTitle: 'Reminders',
    save: 'Save',
    permOff: 'Notifications are off for unsetld.',
    openSettings: 'Open Settings',
  },
  widget: {
    title: 'Put it on your lock screen.',
    tabs: ['Lock Screen', 'Home Screen'] as const,
    lockSteps: [
      'Touch and hold your lock screen, then tap Customize.',
      'Tap Lock Screen, then the space under the clock.',
      'Choose unsetld, then Line.',
    ],
    homeSteps: [
      'Touch and hold an empty spot on your home screen.',
      'Tap Edit, then Add Widget.',
      'Search unsetld and choose a size.',
    ],
    done: 'Done',
    later: 'Later',
    pageTitle: 'Add a widget',
  },
  reader: {
    chapters: 'Chapters',
    menu: {
      share: 'Share',
      copy: 'Copy line',
      save: 'Save',
      unsave: 'Remove from saved',
      cancel: 'Cancel',
    },
    a11y: {
      save: 'Save line',
      unsave: 'Remove from saved',
      share: 'Share line',
      chapters: 'Chapters',
      colorway: 'Colorway',
      record: 'Your record',
      close: 'Close',
      back: 'Back',
    },
  },
  today: {
    work: "TODAY'S WORK",
    count: (done: number, all: number) => `${done} / ${all}`,
    yourStandard: 'Your standard',
    yourTask: 'Your task',
    fromUnsetld: (chapter: string) => `From UNSETLD · ${chapter}`,
    proven: (time: string) => `Proven ${time}`,
    done: (time: string) => `Done ${time}`,
    proveHint: 'Opens the camera to prove it',
    addTask: 'Add a task',
    taskPlaceholder: 'Say it plainly.',
    removeTask: 'Remove',
    locked: 'FULL EDITION',
    footNote: (per: number, max: number) => `Prove a task with a photo. Each one is ${per} points, up to ${per * max} a day.`,
  },
  task: {
    what: (proof: string) => `What to photograph: ${proof.charAt(0).toLowerCase()}${proof.slice(1)}`,
    noPhoto: 'Done, no photo',
    proven: 'Proven.',
    capped: (n: number) => `Proven. Today's ${n} points are in.`,
    markNotDone: 'Mark not done',
    doneAt: (time: string) => `Done ${time}. No photo.`,
  },
  night: {
    label: 'NIGHT CHECK',
    question: 'Did you hold your standard today?',
    held: 'Held',
    notToday: 'Not today',
    heldTitle: 'Held.',
    notedTitle: 'Noted.',
    heldBody: (n: number) => `Day ${n} is on record.`,
    notedBody: (n: number) => `Day ${n} is still on record.`,
  },
  oneTime: {
    access: {
      label: 'ACCESS',
      title: 'The days add up to something.',
      body: 'Day 7 opens early access to every UNSETLD drop. Proof of the work earns points toward codes at unsetld.com. None of it can be bought.',
      link: 'See your record',
    },
  },
  colorway: {
    title: 'Colorway',
    locked: 'FULL EDITION',
    lockedBar: (name: string) => `${name} is part of Full Edition.`,
    seeFull: 'See Full Edition',
  },
  share: {
    tabs: ['Story', 'Post'] as const,
    button: 'Share',
    copy: 'Copy line',
    copied: 'Copied',
    previewNote: 'Sharing opens the iOS share sheet in the app.',
  },
  saved: {
    title: 'Saved',
    remove: 'Remove from saved',
    emptyTitle: 'Nothing saved yet.',
    emptyBody: 'Double-tap a line to keep it here.',
  },
  yours: {
    title: 'Your lines',
    write: 'Write a line',
    placeholder: 'Write the line you need to read.',
    edit: 'Edit',
    delete: 'Delete',
    footnote: 'Your lines stay on this phone. They show up in your reminders and on your widgets.',
    lockedTitle: 'Your lines are part of Full Edition.',
    lockedBody: 'Write the lines you need to read. They show up in your reminders and on your widgets.',
    seeFull: 'See Full Edition',
    max: 110,
  },
  record: {
    settings: 'Settings',
    label: 'RECORD',
    daysOnRecord: (n: number) => (n === 1 ? 'day on record' : 'days on record'),
    today: 'TODAY',
    run: 'RUN',
    longest: 'LONGEST',
    held: 'HELD',
    days: (n: number) => (n === 1 ? 'day' : 'days'),
    of: 'of',
    access: 'Access',
    details: 'Details',
    accessNote: "Earned with days on record. It can't be bought.",
    status: {
      open: 'OPEN',
      used: 'USED',
      paused: 'PAUSED',
      left: (n: number) => (n === 1 ? '1 DAY' : `${n} DAYS`),
    },
    pausedNote: 'Early access is paused. Put 7 days on record to open it again.',
    proof: 'Proof',
    points: (n: number) => (n === 1 ? '1 point' : `${n} points`),
    proofNote: (per: number) => `A photo of each task you prove, taken in the app. Each one is ${per} points.`,
    proofNoteNoPoints: 'A photo of each task you prove, taken in the app. It stays on this phone.',
    provenToday: (n: number) => (n === 1 ? 'Today: 1 task proven.' : `Today: ${n} tasks proven.`),
    seeAll: 'See all',
    codes: 'CODES',
    tierTitle: (percent: number) => `${percent}% off one order`,
    tierSub: (points: number, maxOff: number) => `${points} points. Up to $${maxOff} off at unsetld.com.`,
    tierStatus: {
      ready: 'READY',
      used: 'USED',
      short: (n: number) => `${n} TO GO`,
    },
    codeReady: 'You have enough points for a code.',
    codeLink: 'Get your code',
    useCode: 'Use it at unsetld.com',
    codeExpires: (date: string) => `Works until ${date}. One order.`,
    redeemTitle: (points: number, percent: number) => `Trade ${points} points for ${percent}% off?`,
    redeemBody: (maxOff: number, days: number) => `One order at unsetld.com, up to $${maxOff} off. The code works for ${days} days.`,
    redeemYes: 'Get the code',
    redeemNo: 'Cancel',
    oneEach: 'One code each collection. The next one opens with the next collection.',
    previewCode: 'Preview build: this code is not real.',
  },
  proof: {
    label: 'PROOF',
    title: 'Show the work.',
    body: 'One photo a day, taken now, of the thing you did. It stays on this phone.',
    which: 'WHAT IT PROVES',
    take: 'Take the photo',
    choose: 'Choose a photo',
    previewNote: 'Preview build: pick any photo. The app only takes them live.',
    keep: 'Keep it',
    retake: 'Retake',
    added: 'Proof added.',
    addedBody: (n: number) => `Day ${n} is on record.`,
    pointsLine: (earned: number, total: number) => `+${earned} POINTS · ${total} IN TOTAL`,
    done: 'Done',
    cameraOff: 'Camera is off for unsetld.',
    openSettings: 'Open Settings',
    already: "Today's proof is in.",
    add: 'Add proof',
    galleryTitle: 'Proof',
    galleryEmpty: 'No proof yet.',
    galleryEmptyBody: 'After the night check, add a photo of the work.',
    onPhone: 'Kept on your other phone',
    a11yPhoto: (date: string) => `Proof from ${date}`,
  },
  milestone: {
    termsLink: 'Access terms',
    signInNote: 'Sign in to use access. It takes one tap.',
    usedNote: "You've used this collection's member price. It opens again with the next collection.",
    networkError: "Couldn't reach unsetld.com. Try again in a moment.",
    pausedError: 'Access is paused. Put 7 days on record to open it again.',
    claimedPatch: 'Added. It ships free with your next order.',
  },
  letter: {
    dayLabel: (d: number) => `DAY ${String(d).padStart(3, '0')}`,
    dayTitle: (d: number) => `Day ${d}.`,
    comebackSub: "You came back. That's the part that counts.",
    comebackBody: 'Early access and your member price are open again.',
    close: 'Close',
  },
  paywall: {
    restore: 'Restore',
    label: 'UNSETLD',
    title: 'Full Edition',
    description: 'Every chapter, every colorway, more of your own work.',
    spec: [
      ['CHAPTERS', 'All seven, for your daily task and lines'],
      ['TASKS', 'Up to three more of your own, every day'],
      ['COLORWAYS', 'All ten, in the app and on your widgets'],
      ['REMINDERS', 'Up to ten a day. Write your own lines.'],
    ] as const,
    plans: {
      annual: 'Annual',
      monthly: 'Monthly',
      lifetime: 'Lifetime',
    },
    sub: {
      annualTrial: (days: number) => `${days} days free, then billed yearly`,
      annual: 'Billed yearly',
      monthly: 'Billed monthly',
      lifetime: 'One payment',
    },
    unit: { annual: '/ year', monthly: '/ month', lifetime: 'once' },
    perMonth: (p: string) => `${p} a month`,
    save: (pct: number) => `Save ${pct}%`,
    timeline: (price: string) => [
      ['TODAY', 'Everything opens'],
      ['DAY 2', 'We remind you'],
      ['DAY 3', `${price} billed`],
    ],
    cta: {
      trial: 'Start free trial',
      annual: (p: string) => `Subscribe for ${p} a year`,
      monthly: (p: string) => `Subscribe for ${p} a month`,
      lifetime: (p: string) => `Buy for ${p}`,
    },
    fine: {
      trial: (days: number, p: string) =>
        `${days} days free, then ${p} per year. Renews automatically. Cancel any time in Settings at least 24 hours before the trial ends.`,
      annual: (p: string) => `${p} per year. Renews automatically. Cancel any time in Settings.`,
      monthly: (p: string) => `${p} per month. Renews automatically. Cancel any time in Settings.`,
      lifetime: (p: string) => `One payment of ${p}. No subscription.`,
    },
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    loading: '—',
    priceError: "Prices couldn't load. Check your connection.",
    tryAgain: 'Try again',
    failedTitle: "Purchase didn't go through.",
    failedBody: 'Nothing was charged. Try again in a moment.',
    restored: 'Full Edition restored.',
    noneTitle: 'Nothing to restore.',
    noneBody: "We couldn't find Full Edition on this Apple ID.",
    preview: 'Preview build. No charge.',
  },
  settings: {
    title: 'Settings',
    sections: {
      daily: 'DAILY',
      reading: 'READING',
      widgets: 'WIDGETS',
      unsetld: 'UNSETLD',
      full: 'FULL EDITION',
      about: 'ABOUT',
      tester: 'TESTER',
    },
    reminders: 'Reminders',
    remindersValue: (n: number, a: string, b: string) => (n === 0 ? 'Off' : `${n} a day, ${a} to ${b}`),
    night: 'Night check',
    standard: 'Your standard',
    chapters: 'Chapters',
    colorway: 'Colorway',
    strong: 'Strong language',
    strongNote: 'Some lines swear. They never appear on your lock screen, widgets or notifications.',
    saved: 'Saved',
    yourLines: 'Your lines',
    addWidget: 'Add a widget',
    dropAlerts: 'Drop alerts',
    dropNote: 'Tells you when a collection opens. Separate from your daily reminders. Off unless you turn it on.',
    account: 'Account',
    notSignedIn: 'Not signed in',
    plan: 'Plan',
    free: 'Free',
    restore: 'Restore purchases',
    record: 'How the record works',
    accessTerms: 'Access terms',
    contact: 'Contact',
    contactEmail: 'unsetldclothing@gmail.com',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    footer: (version: string, vol: number) => `unsetld · version ${version} · volume ${String(vol).padStart(3, '0')}`,
    devTools: 'Tester tools',
  },
  account: {
    title: 'Account',
    body: 'You only need an account to use codes and access: discount codes, early access and the patch. Your record, proof photos, saved lines and your lines stay on this phone.',
    legal: "By signing in you confirm you're 18 or over and live in the US.",
    signedIn: (email: string) => `Signed in as ${email}`,
    signOut: 'Sign out',
    error: "Couldn't sign in. Try again in a moment.",
    previewButton: 'Sign in with Apple',
    previewNote: 'Preview build: sign-in is simulated.',
  },
  notifications: {
    night: 'Did you hold your standard today?',
    stillOpen: (task: string) => `Still open: ${task}`,
    held: 'Held',
    notToday: 'Not today',
    trial: (p: string) => `Your free trial ends tomorrow. ${p} for the year starts then. Cancel any time in Settings.`,
    dropEarly: (c: string, when: string) => `Collection ${c} is open to you now. Everyone else gets it ${when}.`,
    dropPublic: (c: string, when: string) => `Collection ${c} opens ${when}.`,
  },
} as const;
